### ISSUE TITLE
Desktop: Text is too wide

### ISSUE THREAD

**Issue by n-kb** [ctt-data/cultural-differences#2]
![screenshot from 2018-12-07 08-47-38](https://user-images.githubusercontent.com/864677/49634442-fb6b7b00-f9fc-11e8-93c4-d0e4602f94fe.png)

On desktop, try to have the text occupy only half of the width of the screen. You can do that using
`<div class="column is-half is-offset-one-quarter">` 
for instance

**Comment by diananicole** [comment]
all set
